"""Create initial tables

Revision ID: 01cc5d7e17b3
Revises: 
Create Date: 2026-06-27 12:02:09.215907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cc5d7e17b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'taxpayers',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('tpin', sa.String(), nullable=False, unique=True),
        sa.Column('taxpayer_type', sa.String(), nullable=False),
        sa.Column('business_name', sa.String(), nullable=True),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('registration_status', sa.String(), server_default=sa.text("'pending'"), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxpayers')
    # ### end Alembic commands ###
