"""Add users table

Revision ID: 816c0fac5095
Revises: 01cc5d7e17b3
Create Date: 2026-06-28 15:50:37.420698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816c0fac5095'
down_revision: Union[str, Sequence[str], None] = '01cc5d7e17b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('taxpayers_tpin_key'), 'taxpayers', type_='unique')
    op.create_index(op.f('ix_taxpayers_id'), 'taxpayers', ['id'], unique=False)
    op.create_index(op.f('ix_taxpayers_tpin'), 'taxpayers', ['tpin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxpayers_tpin'), table_name='taxpayers')
    op.drop_index(op.f('ix_taxpayers_id'), table_name='taxpayers')
    op.create_unique_constraint(op.f('taxpayers_tpin_key'), 'taxpayers', ['tpin'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
